name: PHP Linting
on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: michaelw90/PHP-Lint@master
