name: PHP Linting
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: overtrue/phplint@8.2
        with:
          path: .
          options: --exclude=*.log
